apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: poplwhrav-go 
  janus-idp.io/tekton: poplwhrav-go
  backstage.io/kubernetes-id: poplwhrav-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: poplwhrav-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  