apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: poplwhrav-go-gitops
  description: This is GitOps manifest for poplwhrav-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=poplwhrav-go
    backstage.io/kubernetes-id: poplwhrav-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: poplwhrav-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:poplwhrav-go
