apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: poplwhrav-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: poplwhrav-go 
  name: poplwhrav-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: poplwhrav-go 
